### ISSUE TITLE
GraphQL Client (Multiple) Marvel delay

### ISSUE THREAD

**Issue by jenter** [acquia-pso/decoupledkit-react#4]
The http://localhost:8080/graphqlclientmulti route seems to have a decent delay before loading everything under "List Of Marvel Characters". Is this avoidable or just a symptom of that API fetch?

**Comment by jenter** [comment]
cc @steveworley

**Comment by steveworley** [comment]
The initial request is slow (each character should be cached for 30secs so subsequent requests should be much quicker) the issue here is that we've really extrapolated the number of requests the graphql server makes to build the data and because we have a volatile dev server caching doesn't really do it any good.

So for each character we make a request back to Marvel to get a list of comics and then for each comic we make a request to the comic sales API to get the sales data.

As each character has ~ 15 comics, each character is making 15 additional requests to the comic sales API. If we have 5 characters that could be 75 (5 * 15) requests to build the resource which is where the slowness comes from; ideally we would have resource caching set to something much higher and would have a slow first request. But I think this quickly shows a limitation of decoupled regardless of approach; the more complex the data structures are the more overhead we will have to build resources as a HTTP request is typically slower than a SQL query.

That being said I'll see if there are any tweaks I can make to how the requests are being sent from the graphql server.

**Comment by steveworley** [comment]
An update here - I changed how `ComicSales` fetches the data and to clarify the above. The comic sales endpoint uses it's own IDs to access the data which looks like a request to `/api/titles/{id}/by-issue.json`. To get the id we made a request to their main listing API `/api/titles.json` however this main request is slow due to how many records we get back (like 15k). This was happening for each comic (so 2 request per comic) which really slowed things down. I was averaging around 20seconds for the initial call.

I introduced a new-ish concept into this class to help alleviate this issue (which might be useful for other projects). We leverage `async/await` - this api allows Javascript to block asynchronous operations (a fetch is typically asynchronous) so when the class is instantiated it will block while the initial comic list is loaded which reduces about half of the requests. This has taken the average load time for an unwarmed cache to about 6 seconds.
